runtime: nodejs18
handlers:
  # Serve static files with url ending in .
  - url: /(.*\..+)$
    static_files: dist/\1
    upload: dist/.*\..
  # Catch all handler to index.html
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html